### ISSUE TITLE
Previously fixed issue still happening

### ISSUE THREAD

**Issue by ChrstphGrnr** [learn-co-curriculum/dynamic-orm-lab#24] opened 2019-12-29 01:03 UTC
Today we came across a student in the Online FT (110419) track who still has the already known issue of additional data in the database response going on.

`1) Student has instance methods to insert data into db #save saves the student to the db
     Failure/Error: expect(DB[:conn].execute("SELECT * FROM students WHERE name = 'Sam'")).to eq([{"id"=>1, "name"=>"Sam", "grade"=>11}])
     
       expected: [{"grade"=>11, "id"=>1, "name"=>"Sam"}]
            got: [{"id"=>1, "name"=>"Sam", "grade"=>11, 0=>1, 1=>"Sam", 2=>11}]
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -[{"grade"=>11, "id"=>1, "name"=>"Sam"}]
       +[{"id"=>1, "name"=>"Sam", "grade"=>11, 0=>1, 1=>"Sam", 2=>11}]`

Still not sure what the issue is, even after reading previous PRs and changes in the repo. 
Anyhow, thought I'd bring it to your guys attention.

**Comment by kkterai** [comment] 2020-01-23 21:40
Another student encountered this issue today. Reconfirming that this is still happening.

**Comment by morgvanny** [comment] 2020-02-13 03:51
I think when something changed with sqlite3, it broke a ton of labs. It looks like we fixed this lab to work with the new version, but then realized we didn't want to go through and mess with every lab, so we mass-specified a certain version of the gem, which made this isolated "fix" no longer needed. Not sure if we want to just use the latest version of sqlite3 and update the Gemfile.lock (that works) or if we want to change the specs back to how they were.

**Comment by maxwellbenton** [comment] 2020-02-13 15:40
Thank you @ChrstphGrnr, @kkterai, and @morgvanny!

I've taken a look at this lab and tried to recreate the issue but was unable, even with outdated sqlite versions. It does look like sqlite3 is working fine without a version lock, so I've updated the `Gemfile` and `Gemfile.lock` files. I've also rebased the solution.  The solution is currently working with the latest sqlite and the same starting db files as the master.

Since I can't reproduce, I am not 100% sure this has resolved the issue of this extra data getting added to the results during testing and will leave this issue open for now. 

If any of you happen to know any of the student GitHub accounts that faced this problem, I'd be curious to look at what code they have. 

Some of the tests were originally were written to expect the redundant data (`0=>1, 1=>"Sam", 2=>11`) so at some point, it was the expected output. It is possible a better solution was discovered that gets rid of this, but that multiple students are still discovering an alternate implementation that is causing their code to produce the old results.

**Comment by Saturn226** [comment] 2020-02-14 22:47
Another student informed me that this issue comes up with students using sqlite3 versions 1.3 I had a student update to 1.4.2 and it fixed the problem.

**Comment by gnappo1** [comment] 2020-02-28 04:16
Confirmed what Ashley posted above ☝🏻, update the sqlite3 version and no more weird return value.
Version  1.4.2 worked in my case, but other versions can be tested as well! 
@maxwellbenton some batches get a gemfile version with a specified version `~>1.3.6`, which is the cause of the issue.

**Comment by ashleymader** [comment] 2020-04-21 15:05
I encountered this problem today. I did what gnappo1 said and the tests are now passing.

**Comment by lizbur10** [comment] 2020-05-12 19:26
@maxwellbenton This student had the problem today: https://github.com/murphcoder/dynamic-orm-lab-online-web-sp-000

**Comment by FreeBreadsticks** [comment] 2020-05-18 00:10
Ran into this same error today. Didn't realize this lab will work without running `bundle install`. Fixed by running `bundle install` !

**Comment by lizbur10** [comment] 2020-07-12 13:24
@maxwellbenton This student had the problem today: https://github.com/micahmccallum/dynamic-orm-lab-online-web-sp-000.

**Closed as completed** 2021-08-19 15:32 UTC
