### ISSUE TITLE
Previously closed issue still happeneing.

### ISSUE THREAD

**Issue by JCGuest** [learn-co-curriculum/dynamic-orm-lab#23] opened 2019-10-26 04:37 UTC
"The following spec tests have extra data, it looks like another copy of the data where the keys are indices of the array...its pretty weird. But I am pretty sure they do not belong. Specifically the save, find_by, and find_by_name have this included in their hash in the test: #, 0=>1, 1=>"Susan", 2=>10"

"Summary Student was failing tests based on desired #DB[:conn].execute return values to have redundant values, with the keys being 0,1,2..etc for the redundant values.
Fix We took out all the redundant value pairs with numeric keys, and all of the tests passed. The code was all correct, so I think that it is possible that sqlite3 returns different values for #execute than it did when the lab was first made"

**Comment by maxwellbenton** [comment] 2019-10-28 17:08
Hi @JCGuest,

Thank you for providing this feedback. The extra data was removed from this repository back in July, but on further investigation, it looks like some of the student batch repositories failed to receive the commit with these changes. The v-000 student version of this repository is now aligned in commits with this repo and it looks like our other primary student batches are aligned as well. Students should be receiving the updated specs going forward. 

Since the issue seems to be resolved on this this repository and on the primary student versions, I am going to close this issue, but if you happen to know the batch this student was in, I can confirm that it has been updated.

Thank you for taking the time to provide this feedback!

**Closed as completed by maxwellbenton** 2019-10-28 17:08 UTC
